apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-storage
spec:
  serviceName: "web-storage"
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage-container
          image: gcr.io/exam-458209/storage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: storage-volume
              mountPath: /data/storage
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        storageClassName: "standard"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-storage
spec:
  type: ClusterIP
  # clusterIP: 34.118.229.70
  selector:
    app: storage
  ports:
    - port: 3000
